name: recover-match-secrets
on:
  workflow_dispatch:
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: MATCH_PASSWORD (hex)
        run: |
          echo "MATCH_PASSWORD_HEX<<"
          echo -n "${{ secrets.MATCH_PASSWORD }}" | od -An -tx1 | tr -d ' \n'; echo
          echo ">>"
      - name: MATCH_GIT_BASIC_AUTHORIZATION (hex)
        run: |
          echo "MATCH_GIT_HEX<<"
          echo -n "${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}" | od -An -tx1 | tr -d ' \n'; echo
          echo ">>"
